### ISSUE TITLE
Can't save page edits when theme is active

### ISSUE THREAD

**Issue by sebasvisser** [diomed/casper#2]
For some reason I'm not able to save any page edits (for example add the image, or deleting a line).

As soon as I change the theme to for instance Quark, I'm able to save the page edits.

**Comment by diomed** [comment]
I must tell you.. I'm a bit like you - gluing stuff together. 
so I'm not really sure how to fix this, since I don't know what's causing this 
since this doesn't happen to me, and I'm really bad at troubleshooting for 
the reason above.
I might have to ask around in grav community to let you know.
btw. - please try editing in **expert mode** and see how that goes.
is it the same, or does it save?

**Comment by sebasvisser** [comment]
The best things in the world are hold together with glue ;)

Editing in Expert mode does enable it to save.

**Comment by diomed** [comment]
would you pls check are there any errors in console or logged by grav

**Comment by sebasvisser** [comment]
https://cl.ly/3eb2becd043e
This is what I get after trying to edit the page title..

**Comment by diomed** [comment]
This is fixed now, I believe. [in 0.5]
If you experience any problems, gimme a shout.
